name: Places  
on: [push]
jobs:
  deploy_source:
    name: Deploy API Using Lambda
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true

      - name: /places get lambda deploy zip
        uses: kinlane/places@main
        with:
            args: zip -qq -r m-s-places-g.zip places/get/index.js node_modules
      - name: place get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-east-1
            function_name: m-s-places-g
            zip_file: m-s-places-g.zip
      - name: /places post lambda deploy zip
        uses: kinlane/places@main
        with:
            args: zip -qq -r m-s-places-po.zip places/post/index.js node_modules
      - name: place get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-east-1
            function_name: m-s-places-po
            zip_file: m-s-places-po.zip
      - name: /places/{place_id} get lambda deploy zip
        uses: kinlane/places@main
        with:
            args: zip -qq -r m-s-places-place-g.zip places/place_id/get/index.js node_modules
      - name: place get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-east-1
            function_name: m-s-places-place-g
            zip_file: m-s-places-place-g.zip
      - name: /places/{place_id} put lambda deploy zip
        uses: kinlane/places@main
        with:
            args: zip -qq -r m-s-places-place-pu.zip places/place_id/put/index.js node_modules
      - name: place get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-east-1
            function_name: m-s-places-place-pu
            zip_file: m-s-places-place-pu.zip
      - name: /places/{place_id} delete lambda deploy zip
        uses: kinlane/places@main
        with:
            args: zip -qq -r m-s-places-place-d.zip places/place_id/delete/index.js node_modules
      - name: place get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-east-1
            function_name: m-s-places-place-d
            zip_file: m-s-places-place-d.zip          
      - name: /places/{place_id}/tags get lambda deploy zip
        uses: kinlane/places@main
        with:
            args: zip -qq -r m-s-places-place-tags-g.zip places/place_id/tags/get/index.js node_modules
      - name: places get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-east-1
            function_name: m-s-places-place-tags-g
            zip_file: m-s-places-place-tags-g.zip
      - name: /places/{place_id}/tags post lambda deploy zip
        uses: kinlane/places@main
        with:
            args: zip -qq -r m-s-places-place-tags-po.zip places/place_id/tags/post/index.js node_modules
      - name: places get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-east-1
            function_name: m-s-places-place-tags-po
            zip_file: m-s-places-place-tags-po.zip
      - name: /places/{place_id}/tags/{tag_id} delete lambda deploy zip
        uses: kinlane/places@main
        with:
            args: zip -qq -r m-s-places-place-tags-tag-d.zip places/place_id/tags/tag_id/delete/index.js node_modules
      - name: places get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-east-1
            function_name: m-s-places-place-tags-tag-d
            zip_file: m-s-places-place-tags-tag-d.zip            